package GUI;

import Auxiliar.Erros;
import Auxiliar.ValidaCampos;
import DAO.MovimentoDAO;
import Objetos.Movimento;
import java.sql.SQLException;
import java.util.List;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.PlainDocument;

/**
 *
 * @author asfmegas
 */
public class MovimentoGUI extends javax.swing.JFrame {
    private DefaultTableModel tmMovimento = new DefaultTableModel(null,new String[]{"ID","NOME","NASCIMENTO","CURSO","DISCIPLINA","NOTA 1","NOTA 2","NOTA 3","FALTAS"});
    private int idmov;
    private List<Movimento> listaMov;
    private ListSelectionModel lsmMovimento;
    private boolean permite = false;
    /**
     * Creates new form MovimentoGUI
     */
    private final ButtonGroup bg;
    
    public MovimentoGUI() {
        setTitle("MOVIMENTO - SADA V 1.0");
        
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        
        //Desabilitar campos
        jtNome.setEditable(false);
        jtCurso.setEditable(false);
        jtDisc.setEditable(false);
        jtMedia.setEditable(false);
        jtRFaltas.setEditable(false);
        //foco no jtPesquisa
        jtPesquisa.requestFocus();
        
        //ButtonGrupo
        bg = new ButtonGroup();
        bg.add(jrDisc);
        bg.add(jrCurso);
        bg.add(jrAluno);
        jrAluno.setSelected(true);
        
        jtPesquisa.setDocument(new CustomDocument());
        jtTabela.getTableHeader().setReorderingAllowed(false); 
        int x = 0;
        //tabela.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        jtTabela.getColumnModel().getColumn(x++).setPreferredWidth(20);
        jtTabela.getColumnModel().getColumn(x++).setPreferredWidth(150);
        jtTabela.getColumnModel().getColumn(x++).setPreferredWidth(40);
        jtTabela.getColumnModel().getColumn(x++).setPreferredWidth(80);
        jtTabela.getColumnModel().getColumn(x++).setPreferredWidth(80);
        jtTabela.getColumnModel().getColumn(x++).setPreferredWidth(30);
        jtTabela.getColumnModel().getColumn(x++).setPreferredWidth(30);
        jtTabela.getColumnModel().getColumn(x++).setPreferredWidth(30);
        jtTabela.getColumnModel().getColumn(x++).setPreferredWidth(20);
        
        jtFaltas.setText("0");
        
        infor();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jbAlterar = new javax.swing.JButton();
        jbLimpar = new javax.swing.JButton();
        jbExcluir = new javax.swing.JButton();
        jbFechar = new javax.swing.JButton();
        jbNovo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtTabela = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtNome = new javax.swing.JTextField();
        jtCurso = new javax.swing.JTextField();
        jtDisc = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jtNota3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtNota1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtNota2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtMedia = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jtRFaltas = new javax.swing.JTextField();
        jtFaltas = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jrAluno = new javax.swing.JRadioButton();
        jrCurso = new javax.swing.JRadioButton();
        jrDisc = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jtPesquisa = new javax.swing.JTextField();
        jbConsulta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(51, 51, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jbAlterar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbAlterar.setForeground(new java.awt.Color(0, 0, 204));
        jbAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/alterar-sada.png"))); // NOI18N
        jbAlterar.setText("ALTERAR");
        jbAlterar.setEnabled(false);
        jbAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAlterarActionPerformed(evt);
            }
        });
        jbAlterar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbAlterarKeyPressed(evt);
            }
        });

        jbLimpar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbLimpar.setForeground(new java.awt.Color(0, 0, 204));
        jbLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/limpar-sada.png"))); // NOI18N
        jbLimpar.setText("LIMPAR");
        jbLimpar.setEnabled(false);
        jbLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparActionPerformed(evt);
            }
        });

        jbExcluir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbExcluir.setForeground(new java.awt.Color(0, 0, 204));
        jbExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/excluir-sada.png"))); // NOI18N
        jbExcluir.setText("EXCLUIR");
        jbExcluir.setEnabled(false);
        jbExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExcluirActionPerformed(evt);
            }
        });

        jbFechar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbFechar.setForeground(new java.awt.Color(0, 0, 204));
        jbFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/fechar-sada.png"))); // NOI18N
        jbFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbFecharActionPerformed(evt);
            }
        });

        jbNovo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbNovo.setForeground(new java.awt.Color(0, 0, 204));
        jbNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/novo-sada.png"))); // NOI18N
        jbNovo.setText("NOVO");
        jbNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNovoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbAlterar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbLimpar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbExcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jbExcluir, jbLimpar, jbNovo});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbLimpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbFechar))
                    .addComponent(jbNovo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jtTabela.setModel(tmMovimento);
        jtTabela.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        lsmMovimento = jtTabela.getSelectionModel();
        lsmMovimento.addListSelectionListener(new ListSelectionListener() {

            public void valueChanged(ListSelectionEvent e) {
                if (!e.getValueIsAdjusting()) {
                    selecionarLinhaTabela(jtTabela);
                }
            }
        });
        jScrollPane1.setViewportView(jtTabela);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Nome:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Curso:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Disciplina:");

        jtNome.setBackground(new java.awt.Color(51, 204, 255));
        jtNome.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jtCurso.setBackground(new java.awt.Color(51, 204, 255));
        jtCurso.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jtDisc.setBackground(new java.awt.Color(51, 204, 255));
        jtDisc.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addComponent(jLabel1))
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtDisc, javax.swing.GroupLayout.PREFERRED_SIZE, 797, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 797, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 797, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtDisc))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("NOTA 1");

        jtNota3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jtNota3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtNota3.setEnabled(false);
        jtNota3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtNota3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtNota3FocusLost(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("NOTA 2");

        jtNota1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jtNota1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtNota1.setEnabled(false);
        jtNota1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtNota1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtNota1FocusLost(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("NOTA 3");

        jtNota2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jtNota2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtNota2.setEnabled(false);
        jtNota2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtNota2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtNota2FocusLost(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("MÉDIA");

        jtMedia.setBackground(new java.awt.Color(51, 204, 255));
        jtMedia.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jtMedia.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("+");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("+");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("/3 =");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("FALTA(S)");

        jtRFaltas.setBackground(new java.awt.Color(51, 204, 255));
        jtRFaltas.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jtRFaltas.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jtFaltas.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jtFaltas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtFaltas.setEnabled(false);
        jtFaltas.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtFaltasFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtFaltasFocusLost(evt);
            }
        });
        jtFaltas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtFaltasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jtNota1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10)))
                .addGap(11, 11, 11)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jtNota2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel11))
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jtNota3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel12))
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtMedia, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(49, 49, 49)
                .addComponent(jtFaltas, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtRFaltas, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jtNota1, jtNota2, jtNota3, jtRFaltas});

        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtFaltas, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtNota1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtNota2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtNota3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10)
                        .addComponent(jLabel11)
                        .addComponent(jLabel12)
                        .addComponent(jtMedia)
                        .addComponent(jtRFaltas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jtMedia, jtNota1, jtNota2, jtNota3});

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Pesquisa"));

        jrAluno.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jrAluno.setText("Aluno");
        jrAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrAlunoActionPerformed(evt);
            }
        });

        jrCurso.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jrCurso.setText("Curso");
        jrCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrCursoActionPerformed(evt);
            }
        });

        jrDisc.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jrDisc.setText("Disciplina");
        jrDisc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrDiscActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("NOME:");

        jtPesquisa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtPesquisaActionPerformed(evt);
            }
        });

        jbConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/pesquisa-sada.png"))); // NOI18N
        jbConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConsultaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jrAluno)
                        .addGap(16, 16, 16)
                        .addComponent(jrCurso)
                        .addGap(18, 18, 18)
                        .addComponent(jrDisc))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtPesquisa)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbConsulta)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jrAluno)
                            .addComponent(jrCurso)
                            .addComponent(jrDisc))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExcluirActionPerformed
        if(confirmarSalvarDados()){
            int resp = JOptionPane.showConfirmDialog(this, "Deseja excluir o movimento?\n","Confirmação",JOptionPane.YES_NO_OPTION);
            if(resp == JOptionPane.YES_NO_OPTION){
                excluirMov();
            }
        }else{
            JOptionPane.showMessageDialog(null, "Selecione um movimento para a exclusão!");
        }
    }//GEN-LAST:event_jbExcluirActionPerformed

    private void jbFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbFecharActionPerformed
        Principal gui = new Principal();
        gui.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jbFecharActionPerformed

    private void jtFaltasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtFaltasActionPerformed
        
    }//GEN-LAST:event_jtFaltasActionPerformed

    private void jbNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNovoActionPerformed
        CadastroMovGUI gui = new CadastroMovGUI();
        limparCampos();
        gui.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jbNovoActionPerformed

    private void jbConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConsultaActionPerformed
        try {
            listarMov();
        } catch (SQLException ex) {
            Logger.getLogger(MovimentoGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbConsultaActionPerformed

    private void jrAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrAlunoActionPerformed
        getCampo();
    }//GEN-LAST:event_jrAlunoActionPerformed

    private void jrCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrCursoActionPerformed
        getCampo();
    }//GEN-LAST:event_jrCursoActionPerformed

    private void jrDiscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrDiscActionPerformed
        getCampo();
    }//GEN-LAST:event_jrDiscActionPerformed

    private void jbAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAlterarActionPerformed
        if(permite){
            if(confirmarSalvarDados()){
                alterarMov();
            }else{
                JOptionPane.showMessageDialog(null, "Selecione um movimento.");
            }
        }
    }//GEN-LAST:event_jbAlterarActionPerformed

    private void jtNota1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtNota1FocusGained
        jtNota1.selectAll();
    }//GEN-LAST:event_jtNota1FocusGained

    private void jtNota2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtNota2FocusGained
        jtNota2.selectAll();
    }//GEN-LAST:event_jtNota2FocusGained

    private void jtNota3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtNota3FocusGained
        jtNota3.selectAll();
    }//GEN-LAST:event_jtNota3FocusGained

    private void jbLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparActionPerformed
        if(confirmarSalvarDados()){
            lismparCampos();
        }else{
            JOptionPane.showMessageDialog(null, "Selecione um movimento.");
        }
    }//GEN-LAST:event_jbLimparActionPerformed

    private void jtNota3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtNota3FocusLost
        validarNota3();
    }//GEN-LAST:event_jtNota3FocusLost

    private void jtFaltasFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtFaltasFocusLost
        ValidaCampos vc = new ValidaCampos();
        if(vc.validarNumerosInteiros(jtFaltas.getText()) == false){
            jtFaltas.requestFocus();
        }else {
            jbAlterar.requestFocus();
        }     
    }//GEN-LAST:event_jtFaltasFocusLost

    private void jbAlterarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbAlterarKeyPressed
        if(permite){
            if(confirmarSalvarDados()){
                alterarMov();
            }else{
                JOptionPane.showMessageDialog(null, "Selecione um movimento.");
            }
        }
    }//GEN-LAST:event_jbAlterarKeyPressed

    private void jtPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtPesquisaActionPerformed
        try {
            listarMov();
        } catch (SQLException ex) {
            Logger.getLogger(MovimentoGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jtPesquisaActionPerformed

    private void jtNota1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtNota1FocusLost
        validarNota1();
    }//GEN-LAST:event_jtNota1FocusLost

    private void jtNota2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtNota2FocusLost
        validarNota2();
    }//GEN-LAST:event_jtNota2FocusLost

    private void jtFaltasFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtFaltasFocusGained
        jtFaltas.selectAll();
    }//GEN-LAST:event_jtFaltasFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MovimentoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MovimentoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MovimentoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MovimentoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MovimentoGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbAlterar;
    private javax.swing.JButton jbConsulta;
    private javax.swing.JButton jbExcluir;
    private javax.swing.JButton jbFechar;
    private javax.swing.JButton jbLimpar;
    private javax.swing.JButton jbNovo;
    private javax.swing.JRadioButton jrAluno;
    private javax.swing.JRadioButton jrCurso;
    private javax.swing.JRadioButton jrDisc;
    private javax.swing.JTextField jtCurso;
    private javax.swing.JTextField jtDisc;
    private javax.swing.JTextField jtFaltas;
    private javax.swing.JTextField jtMedia;
    private javax.swing.JTextField jtNome;
    private javax.swing.JTextField jtNota1;
    private javax.swing.JTextField jtNota2;
    private javax.swing.JTextField jtNota3;
    private javax.swing.JTextField jtPesquisa;
    private javax.swing.JTextField jtRFaltas;
    private javax.swing.JTable jtTabela;
    // End of variables declaration//GEN-END:variables

    private void lismparCampos() {
        jtPesquisa.setText("");
        jtNota1.setText("");
        jtNota2.setText("");
        jtNota3.setText("");
        jtMedia.setText("");
        jtFaltas.setText("0");
        jtRFaltas.setText("0");
    }
    
    //Classe para manter caixa alta no JTextField
    //Referência
    //http://www.guj.com.br/java/199701-jtextfield-com-caixa-altaresolvido
    public class CustomDocument extends PlainDocument {

        @Override
	public void insertString(int offset, String str, AttributeSet attr)
			throws BadLocationException {
		if (str == null)
			return;
		super.insertString(offset, str.toUpperCase(), attr); // Detalhe no str
	}
    }
    
    public void ativarCampos(){
        jtNota1.setEnabled(true);
        jtNota2.setEnabled(true);
        jtNota3.setEnabled(true);
        jtFaltas.setEnabled(true);
        jbAlterar.setEnabled(true);
        jbLimpar.setEnabled(true);
        jbExcluir.setEnabled(true);
    }
    
    private void limparCampos(){
        jtNome.setText("");
        jtCurso.setText("");
        jtDisc.setText("");
        jtNota1.setText("");
        jtNota2.setText("");
        jtNota3.setText("");
        jtRFaltas.setText("");
        jtFaltas.setText("");
    }
    
    private void listarMov() throws SQLException{
        MovimentoDAO dao = new MovimentoDAO();
        listaMov = dao.pesquisar(getCampo(),"%"+jtPesquisa.getText()+"%");
        moastrarPesquisa(listaMov);
    }
//"ID","NOME","NASCIMENTO","CURSO","DISCIPLINA","NOTA 1","NOTA 2","NOTA 3","FALTAS"
    private void moastrarPesquisa(List<Movimento> mov) {
        while(tmMovimento.getRowCount() > 0){
            tmMovimento.removeRow(0);
        }
        if(mov.isEmpty()){
            JOptionPane.showMessageDialog(null, "Sua lista está vazia!");
        }else{
            String[] linhas = new String[]{null,null,null,null,null,null,null,null};
            for(int i=0; i < mov.size();i++){
                tmMovimento.addRow(linhas);
                tmMovimento.setValueAt(mov.get(i).getId(), i, 0);
                tmMovimento.setValueAt(mov.get(i).getNome(), i, 1);
                tmMovimento.setValueAt(formatarDataCampo(mov.get(i).getData()), i, 2);
                tmMovimento.setValueAt(mov.get(i).getNomeCurso(), i, 3);
                tmMovimento.setValueAt(mov.get(i).getNomeDisc(), i, 4);
                tmMovimento.setValueAt(mov.get(i).getNota1(), i, 5);
                tmMovimento.setValueAt(mov.get(i).getNota2(), i, 6);
                tmMovimento.setValueAt(mov.get(i).getNota3(), i, 7);
                tmMovimento.setValueAt(mov.get(i).getFaltas(), i, 8);
            }
        }
    }
    
    private void selecionarLinhaTabela(JTable tabela){
        if(jtTabela.getSelectedRow() != -1){
            ativarCampos();
            jtNome.setText(listaMov.get(tabela.getSelectedRow()).getNome());
            jtCurso.setText(listaMov.get(tabela.getSelectedRow()).getNomeCurso());
            jtDisc.setText(listaMov.get(tabela.getSelectedRow()).getNomeDisc());
            jtNota1.setText(""+listaMov.get(tabela.getSelectedRow()).getNota1());
            System.out.println("Valor nota: "+listaMov.get(tabela.getSelectedRow()).getNota1());
            jtNota2.setText(""+listaMov.get(tabela.getSelectedRow()).getNota2());
            jtNota3.setText(""+listaMov.get(tabela.getSelectedRow()).getNota3());
            jtRFaltas.setText(""+listaMov.get(tabela.getSelectedRow()).getFaltas());
            idmov = listaMov.get(tabela.getSelectedRow()).getIdMov();
            jtMedia.setText(""+calcularMedia());
            jtFaltas.setText("0");
        }else{
            jtNome.setText("");
            jtCurso.setText("");
            jtDisc.setText("");
            jtNota1.setText("");
            jtNota2.setText("");
            jtNota3.setText("");
            jtRFaltas.setText("");  
        }
    }
    
    private String getCampo(){
        String campo = "";
        if(jrAluno.isSelected()){
            campo = "a.nome";
        }else if(jrCurso.isSelected()){
            campo = "c.especificacao";
        }else if(jrDisc.isSelected()){
            campo = "d.especificacao";
        }
        return campo;
    }
    /**
     * Formatacao de double para duas casas decimais retirada do forum
     * http://www.guj.com.br/java/296574-restringir-double-para-apenas-duas-casas-decimais
     * acessado em 24-09-2014
     * @return 
     */
    private double calcularMedia(){
        try{
            double nota1 = Double.parseDouble(jtNota1.getText());
            double nota2 = Double.parseDouble(jtNota2.getText());
            double nota3 = Double.parseDouble(jtNota3.getText());
            double media = (nota1+nota2+nota3)/3;
            return Double.valueOf(String.format(Locale.US, "%.2f", media));
        
        }catch(NumberFormatException e){
            //JOptionPane.showMessageDialog(null, "Erro fatal.\n"+e.getMessage());
            return 0;
        }
    }
    
    private int calcularFaltas(){
        int faltasCadastradas = 0;
        int faltasAcrescentadas = 0;
        if(!jtFaltas.equals("")){
            faltasCadastradas = Integer.parseInt(jtFaltas.getText());
            faltasAcrescentadas = Integer.parseInt(jtRFaltas.getText());
        }
        return faltasCadastradas + faltasAcrescentadas;
    }
    
    private void alterarMov(){
        Movimento mov = new Movimento();
        MovimentoDAO dao = new MovimentoDAO();
        mov.setIdMov(idmov);
        mov.setNota1(Double.parseDouble(jtNota1.getText()));
        mov.setNota2(Double.parseDouble(jtNota2.getText()));
        mov.setNota3(Double.parseDouble(jtNota3.getText()));
        mov.setFaltas(calcularFaltas());
        dao.alterar(mov);
        jtFaltas.setText("0");
        limparCampos();
        try {
            listarMov();
        } catch (SQLException ex) {
            Erros.erroSql("Erro ao tentar alterar dados!\n"+ex.getMessage());
        }
        jtMedia.setText("");
    }
    
    private void excluirMov(){
        MovimentoDAO dao = new MovimentoDAO();
        dao.excluir(idmov);
        jtFaltas.setText("0");
        limparCampos();
        try {
            listarMov();
        } catch (SQLException ex) {
            Erros.erroSql("Erro ao tentar excluir dados!\n"+ex.getMessage());
        }
        jtMedia.setText("");
    }
    
    private String formatarDataCampo(String data){
        char[] num = new char[data.length()];
        for(int i=0; i < data.length(); i++){
            num[i] = data.charAt(i);
        }
        String dia = ""+num[8]+num[9];
        String mes = ""+num[5]+num[6];
        String ano = ""+num[0]+num[1]+num[2]+num[3];
        String d = dia+"/"+mes+"/"+ano;
            //1983-02-18
            //0 1 2 3 - 5 6 - 8 9
        return d;
    }
    
    private void validarNota1(){
        ValidaCampos vc = new ValidaCampos();
        if(jtNota1.getText().equals(""))
            jtNota1.setText("0");
        
        if(vc.validarNota(jtNota1.getText())){
            if(vc.validarNumeros(jtNota1.getText()) == false){
                String novoTexto = jtNota1.getText().replace(',','.');
                permite = true;
                jtNota1.setText(novoTexto);
                jtMedia.setText(""+calcularMedia());
            }else{
                permite = true;
                jtMedia.setText(""+calcularMedia());
            }
        }else{
            JOptionPane.showMessageDialog(null, "Valor inválido para este campo de notas.");
            jtNota1.requestFocus();
            jtNota1.selectAll();
        }
    }
    
    private void validarNota2(){
        ValidaCampos vc = new ValidaCampos();
        if(jtNota2.getText().equals(""))
            jtNota2.setText("0");
        
        if(vc.validarNota(jtNota2.getText())){
            if(vc.validarNumeros(jtNota2.getText()) == false){
                String novoTexto = jtNota2.getText().replace(',','.');
                permite = true;
                jtNota2.setText(novoTexto);
                jtMedia.setText(""+calcularMedia());
            }else{
                permite = true;
                jtMedia.setText(""+calcularMedia());
            }
        }else{
            JOptionPane.showMessageDialog(null, "Valor inválido para este campo de notas.");
            jtNota2.requestFocus();
            jtNota2.selectAll();
        }
    }
    
    private void validarNota3(){
        ValidaCampos vc = new ValidaCampos();
        if(jtNota3.getText().equals(""))
            jtNota3.setText("0");
        
        if(vc.validarNota(jtNota3.getText())){
            if(vc.validarNumeros(jtNota3.getText()) == false){
                String novoTexto = jtNota3.getText().replace(',','.');
                permite = true;
                jtNota3.setText(novoTexto);
                jtMedia.setText(""+calcularMedia());
            }else{
                permite = true;
                jtMedia.setText(""+calcularMedia());
            }
        }else{
            JOptionPane.showMessageDialog(null, "Valor inválido para este campo de notas.");
            jtNota3.requestFocus();
            jtNota3.selectAll();
        }
    }
    
    private void infor(){
        jbAlterar.setToolTipText("Alterar dados.");
        jbExcluir.setToolTipText("Excluir dados.");
        jbNovo.setToolTipText("Novo cadastro.");
        jbLimpar.setToolTipText("Limpar campos.");
    }
    
    private boolean confirmarSalvarDados(){
        if(!jtDisc.getText().equals("") && !jtNome.getText().equals("") && !jtCurso.getText().equals("")){
            return true;
        }else{
            return false;
        }
    }
}
